// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CSProtoPkgBodyDef.proto

#ifndef PROTOBUF_CSProtoPkgBodyDef_2eproto__INCLUDED
#define PROTOBUF_CSProtoPkgBodyDef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace CSProtocol {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

class CSMsgPkgBody;
class CSMsgPkgHeartBeatReq;
class CSMsgPkgHeartBeatRsp;
class CSMsgPkgLoginReq;
class CSMsgPkgLoginRsp;
class CSMsgPkgRegisterReq;
class CSMsgPkgRegisterRsp;

enum CSMsgIDDef {
  CSMsg_None = 0,
  CSMsg_HeartBeatReq = 10001,
  CSMsg_HeartBeatRsp = 10002,
  CSMsg_LoginReq = 10003,
  CSMsg_LoginRsp = 10004,
  CSMsg_RegisterReq = 10005,
  CSMsg_RegisterRsp = 10006,
  CSMsgIDDef_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CSMsgIDDef_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CSMsgIDDef_IsValid(int value);
const CSMsgIDDef CSMsgIDDef_MIN = CSMsg_None;
const CSMsgIDDef CSMsgIDDef_MAX = CSMsg_RegisterRsp;
const int CSMsgIDDef_ARRAYSIZE = CSMsgIDDef_MAX + 1;

const ::google::protobuf::EnumDescriptor* CSMsgIDDef_descriptor();
inline const ::std::string& CSMsgIDDef_Name(CSMsgIDDef value) {
  return ::google::protobuf::internal::NameOfEnum(
    CSMsgIDDef_descriptor(), value);
}
inline bool CSMsgIDDef_Parse(
    const ::std::string& name, CSMsgIDDef* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CSMsgIDDef>(
    CSMsgIDDef_descriptor(), name, value);
}
// ===================================================================

class CSMsgPkgHeartBeatReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSProtocol.CSMsgPkgHeartBeatReq) */ {
 public:
  CSMsgPkgHeartBeatReq();
  virtual ~CSMsgPkgHeartBeatReq();

  CSMsgPkgHeartBeatReq(const CSMsgPkgHeartBeatReq& from);

  inline CSMsgPkgHeartBeatReq& operator=(const CSMsgPkgHeartBeatReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSMsgPkgHeartBeatReq& default_instance();

  void Swap(CSMsgPkgHeartBeatReq* other);

  // implements Message ----------------------------------------------

  inline CSMsgPkgHeartBeatReq* New() const { return New(NULL); }

  CSMsgPkgHeartBeatReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSMsgPkgHeartBeatReq& from);
  void MergeFrom(const CSMsgPkgHeartBeatReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSMsgPkgHeartBeatReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSProtocol.CSMsgPkgHeartBeatReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

  void InitAsDefaultInstance();
  static CSMsgPkgHeartBeatReq* default_instance_;
};
// -------------------------------------------------------------------

class CSMsgPkgHeartBeatRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSProtocol.CSMsgPkgHeartBeatRsp) */ {
 public:
  CSMsgPkgHeartBeatRsp();
  virtual ~CSMsgPkgHeartBeatRsp();

  CSMsgPkgHeartBeatRsp(const CSMsgPkgHeartBeatRsp& from);

  inline CSMsgPkgHeartBeatRsp& operator=(const CSMsgPkgHeartBeatRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSMsgPkgHeartBeatRsp& default_instance();

  void Swap(CSMsgPkgHeartBeatRsp* other);

  // implements Message ----------------------------------------------

  inline CSMsgPkgHeartBeatRsp* New() const { return New(NULL); }

  CSMsgPkgHeartBeatRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSMsgPkgHeartBeatRsp& from);
  void MergeFrom(const CSMsgPkgHeartBeatRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSMsgPkgHeartBeatRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSProtocol.CSMsgPkgHeartBeatRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

  void InitAsDefaultInstance();
  static CSMsgPkgHeartBeatRsp* default_instance_;
};
// -------------------------------------------------------------------

class CSMsgPkgLoginReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSProtocol.CSMsgPkgLoginReq) */ {
 public:
  CSMsgPkgLoginReq();
  virtual ~CSMsgPkgLoginReq();

  CSMsgPkgLoginReq(const CSMsgPkgLoginReq& from);

  inline CSMsgPkgLoginReq& operator=(const CSMsgPkgLoginReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSMsgPkgLoginReq& default_instance();

  void Swap(CSMsgPkgLoginReq* other);

  // implements Message ----------------------------------------------

  inline CSMsgPkgLoginReq* New() const { return New(NULL); }

  CSMsgPkgLoginReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSMsgPkgLoginReq& from);
  void MergeFrom(const CSMsgPkgLoginReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSMsgPkgLoginReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSProtocol.CSMsgPkgLoginReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

  void InitAsDefaultInstance();
  static CSMsgPkgLoginReq* default_instance_;
};
// -------------------------------------------------------------------

class CSMsgPkgLoginRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSProtocol.CSMsgPkgLoginRsp) */ {
 public:
  CSMsgPkgLoginRsp();
  virtual ~CSMsgPkgLoginRsp();

  CSMsgPkgLoginRsp(const CSMsgPkgLoginRsp& from);

  inline CSMsgPkgLoginRsp& operator=(const CSMsgPkgLoginRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSMsgPkgLoginRsp& default_instance();

  void Swap(CSMsgPkgLoginRsp* other);

  // implements Message ----------------------------------------------

  inline CSMsgPkgLoginRsp* New() const { return New(NULL); }

  CSMsgPkgLoginRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSMsgPkgLoginRsp& from);
  void MergeFrom(const CSMsgPkgLoginRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSMsgPkgLoginRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSProtocol.CSMsgPkgLoginRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

  void InitAsDefaultInstance();
  static CSMsgPkgLoginRsp* default_instance_;
};
// -------------------------------------------------------------------

class CSMsgPkgRegisterReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSProtocol.CSMsgPkgRegisterReq) */ {
 public:
  CSMsgPkgRegisterReq();
  virtual ~CSMsgPkgRegisterReq();

  CSMsgPkgRegisterReq(const CSMsgPkgRegisterReq& from);

  inline CSMsgPkgRegisterReq& operator=(const CSMsgPkgRegisterReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSMsgPkgRegisterReq& default_instance();

  void Swap(CSMsgPkgRegisterReq* other);

  // implements Message ----------------------------------------------

  inline CSMsgPkgRegisterReq* New() const { return New(NULL); }

  CSMsgPkgRegisterReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSMsgPkgRegisterReq& from);
  void MergeFrom(const CSMsgPkgRegisterReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSMsgPkgRegisterReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSProtocol.CSMsgPkgRegisterReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

  void InitAsDefaultInstance();
  static CSMsgPkgRegisterReq* default_instance_;
};
// -------------------------------------------------------------------

class CSMsgPkgRegisterRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSProtocol.CSMsgPkgRegisterRsp) */ {
 public:
  CSMsgPkgRegisterRsp();
  virtual ~CSMsgPkgRegisterRsp();

  CSMsgPkgRegisterRsp(const CSMsgPkgRegisterRsp& from);

  inline CSMsgPkgRegisterRsp& operator=(const CSMsgPkgRegisterRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSMsgPkgRegisterRsp& default_instance();

  void Swap(CSMsgPkgRegisterRsp* other);

  // implements Message ----------------------------------------------

  inline CSMsgPkgRegisterRsp* New() const { return New(NULL); }

  CSMsgPkgRegisterRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSMsgPkgRegisterRsp& from);
  void MergeFrom(const CSMsgPkgRegisterRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSMsgPkgRegisterRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CSProtocol.CSMsgPkgRegisterRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

  void InitAsDefaultInstance();
  static CSMsgPkgRegisterRsp* default_instance_;
};
// -------------------------------------------------------------------

class CSMsgPkgBody : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSProtocol.CSMsgPkgBody) */ {
 public:
  CSMsgPkgBody();
  virtual ~CSMsgPkgBody();

  CSMsgPkgBody(const CSMsgPkgBody& from);

  inline CSMsgPkgBody& operator=(const CSMsgPkgBody& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSMsgPkgBody& default_instance();

  void Swap(CSMsgPkgBody* other);

  // implements Message ----------------------------------------------

  inline CSMsgPkgBody* New() const { return New(NULL); }

  CSMsgPkgBody* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSMsgPkgBody& from);
  void MergeFrom(const CSMsgPkgBody& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSMsgPkgBody* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CSProtocol.CSMsgPkgHeartBeatReq csMsgPkgHeartBeatReq = 1;
  bool has_csmsgpkgheartbeatreq() const;
  void clear_csmsgpkgheartbeatreq();
  static const int kCsMsgPkgHeartBeatReqFieldNumber = 1;
  const ::CSProtocol::CSMsgPkgHeartBeatReq& csmsgpkgheartbeatreq() const;
  ::CSProtocol::CSMsgPkgHeartBeatReq* mutable_csmsgpkgheartbeatreq();
  ::CSProtocol::CSMsgPkgHeartBeatReq* release_csmsgpkgheartbeatreq();
  void set_allocated_csmsgpkgheartbeatreq(::CSProtocol::CSMsgPkgHeartBeatReq* csmsgpkgheartbeatreq);

  // optional .CSProtocol.CSMsgPkgHeartBeatRsp csMsgPkgHeartBeatRsp = 2;
  bool has_csmsgpkgheartbeatrsp() const;
  void clear_csmsgpkgheartbeatrsp();
  static const int kCsMsgPkgHeartBeatRspFieldNumber = 2;
  const ::CSProtocol::CSMsgPkgHeartBeatRsp& csmsgpkgheartbeatrsp() const;
  ::CSProtocol::CSMsgPkgHeartBeatRsp* mutable_csmsgpkgheartbeatrsp();
  ::CSProtocol::CSMsgPkgHeartBeatRsp* release_csmsgpkgheartbeatrsp();
  void set_allocated_csmsgpkgheartbeatrsp(::CSProtocol::CSMsgPkgHeartBeatRsp* csmsgpkgheartbeatrsp);

  // optional .CSProtocol.CSMsgPkgLoginReq csMsgPkgLoginReq = 3;
  bool has_csmsgpkgloginreq() const;
  void clear_csmsgpkgloginreq();
  static const int kCsMsgPkgLoginReqFieldNumber = 3;
  const ::CSProtocol::CSMsgPkgLoginReq& csmsgpkgloginreq() const;
  ::CSProtocol::CSMsgPkgLoginReq* mutable_csmsgpkgloginreq();
  ::CSProtocol::CSMsgPkgLoginReq* release_csmsgpkgloginreq();
  void set_allocated_csmsgpkgloginreq(::CSProtocol::CSMsgPkgLoginReq* csmsgpkgloginreq);

  // optional .CSProtocol.CSMsgPkgLoginRsp csMsgPkgLoginRsp = 4;
  bool has_csmsgpkgloginrsp() const;
  void clear_csmsgpkgloginrsp();
  static const int kCsMsgPkgLoginRspFieldNumber = 4;
  const ::CSProtocol::CSMsgPkgLoginRsp& csmsgpkgloginrsp() const;
  ::CSProtocol::CSMsgPkgLoginRsp* mutable_csmsgpkgloginrsp();
  ::CSProtocol::CSMsgPkgLoginRsp* release_csmsgpkgloginrsp();
  void set_allocated_csmsgpkgloginrsp(::CSProtocol::CSMsgPkgLoginRsp* csmsgpkgloginrsp);

  // optional .CSProtocol.CSMsgPkgRegisterReq csMsgPkgRegisterReq = 5;
  bool has_csmsgpkgregisterreq() const;
  void clear_csmsgpkgregisterreq();
  static const int kCsMsgPkgRegisterReqFieldNumber = 5;
  const ::CSProtocol::CSMsgPkgRegisterReq& csmsgpkgregisterreq() const;
  ::CSProtocol::CSMsgPkgRegisterReq* mutable_csmsgpkgregisterreq();
  ::CSProtocol::CSMsgPkgRegisterReq* release_csmsgpkgregisterreq();
  void set_allocated_csmsgpkgregisterreq(::CSProtocol::CSMsgPkgRegisterReq* csmsgpkgregisterreq);

  // optional .CSProtocol.CSMsgPkgRegisterRsp csMsgPkgRegisterRsp = 6;
  bool has_csmsgpkgregisterrsp() const;
  void clear_csmsgpkgregisterrsp();
  static const int kCsMsgPkgRegisterRspFieldNumber = 6;
  const ::CSProtocol::CSMsgPkgRegisterRsp& csmsgpkgregisterrsp() const;
  ::CSProtocol::CSMsgPkgRegisterRsp* mutable_csmsgpkgregisterrsp();
  ::CSProtocol::CSMsgPkgRegisterRsp* release_csmsgpkgregisterrsp();
  void set_allocated_csmsgpkgregisterrsp(::CSProtocol::CSMsgPkgRegisterRsp* csmsgpkgregisterrsp);

  // @@protoc_insertion_point(class_scope:CSProtocol.CSMsgPkgBody)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::CSProtocol::CSMsgPkgHeartBeatReq* csmsgpkgheartbeatreq_;
  ::CSProtocol::CSMsgPkgHeartBeatRsp* csmsgpkgheartbeatrsp_;
  ::CSProtocol::CSMsgPkgLoginReq* csmsgpkgloginreq_;
  ::CSProtocol::CSMsgPkgLoginRsp* csmsgpkgloginrsp_;
  ::CSProtocol::CSMsgPkgRegisterReq* csmsgpkgregisterreq_;
  ::CSProtocol::CSMsgPkgRegisterRsp* csmsgpkgregisterrsp_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto();
  friend void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto();

  void InitAsDefaultInstance();
  static CSMsgPkgBody* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgHeartBeatReq

// -------------------------------------------------------------------

// CSMsgPkgHeartBeatRsp

// -------------------------------------------------------------------

// CSMsgPkgLoginReq

// -------------------------------------------------------------------

// CSMsgPkgLoginRsp

// -------------------------------------------------------------------

// CSMsgPkgRegisterReq

// -------------------------------------------------------------------

// CSMsgPkgRegisterRsp

// -------------------------------------------------------------------

// CSMsgPkgBody

// optional .CSProtocol.CSMsgPkgHeartBeatReq csMsgPkgHeartBeatReq = 1;
inline bool CSMsgPkgBody::has_csmsgpkgheartbeatreq() const {
  return !_is_default_instance_ && csmsgpkgheartbeatreq_ != NULL;
}
inline void CSMsgPkgBody::clear_csmsgpkgheartbeatreq() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgheartbeatreq_ != NULL) delete csmsgpkgheartbeatreq_;
  csmsgpkgheartbeatreq_ = NULL;
}
inline const ::CSProtocol::CSMsgPkgHeartBeatReq& CSMsgPkgBody::csmsgpkgheartbeatreq() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
  return csmsgpkgheartbeatreq_ != NULL ? *csmsgpkgheartbeatreq_ : *default_instance_->csmsgpkgheartbeatreq_;
}
inline ::CSProtocol::CSMsgPkgHeartBeatReq* CSMsgPkgBody::mutable_csmsgpkgheartbeatreq() {
  
  if (csmsgpkgheartbeatreq_ == NULL) {
    csmsgpkgheartbeatreq_ = new ::CSProtocol::CSMsgPkgHeartBeatReq;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
  return csmsgpkgheartbeatreq_;
}
inline ::CSProtocol::CSMsgPkgHeartBeatReq* CSMsgPkgBody::release_csmsgpkgheartbeatreq() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
  
  ::CSProtocol::CSMsgPkgHeartBeatReq* temp = csmsgpkgheartbeatreq_;
  csmsgpkgheartbeatreq_ = NULL;
  return temp;
}
inline void CSMsgPkgBody::set_allocated_csmsgpkgheartbeatreq(::CSProtocol::CSMsgPkgHeartBeatReq* csmsgpkgheartbeatreq) {
  delete csmsgpkgheartbeatreq_;
  csmsgpkgheartbeatreq_ = csmsgpkgheartbeatreq;
  if (csmsgpkgheartbeatreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
}

// optional .CSProtocol.CSMsgPkgHeartBeatRsp csMsgPkgHeartBeatRsp = 2;
inline bool CSMsgPkgBody::has_csmsgpkgheartbeatrsp() const {
  return !_is_default_instance_ && csmsgpkgheartbeatrsp_ != NULL;
}
inline void CSMsgPkgBody::clear_csmsgpkgheartbeatrsp() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgheartbeatrsp_ != NULL) delete csmsgpkgheartbeatrsp_;
  csmsgpkgheartbeatrsp_ = NULL;
}
inline const ::CSProtocol::CSMsgPkgHeartBeatRsp& CSMsgPkgBody::csmsgpkgheartbeatrsp() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
  return csmsgpkgheartbeatrsp_ != NULL ? *csmsgpkgheartbeatrsp_ : *default_instance_->csmsgpkgheartbeatrsp_;
}
inline ::CSProtocol::CSMsgPkgHeartBeatRsp* CSMsgPkgBody::mutable_csmsgpkgheartbeatrsp() {
  
  if (csmsgpkgheartbeatrsp_ == NULL) {
    csmsgpkgheartbeatrsp_ = new ::CSProtocol::CSMsgPkgHeartBeatRsp;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
  return csmsgpkgheartbeatrsp_;
}
inline ::CSProtocol::CSMsgPkgHeartBeatRsp* CSMsgPkgBody::release_csmsgpkgheartbeatrsp() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
  
  ::CSProtocol::CSMsgPkgHeartBeatRsp* temp = csmsgpkgheartbeatrsp_;
  csmsgpkgheartbeatrsp_ = NULL;
  return temp;
}
inline void CSMsgPkgBody::set_allocated_csmsgpkgheartbeatrsp(::CSProtocol::CSMsgPkgHeartBeatRsp* csmsgpkgheartbeatrsp) {
  delete csmsgpkgheartbeatrsp_;
  csmsgpkgheartbeatrsp_ = csmsgpkgheartbeatrsp;
  if (csmsgpkgheartbeatrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
}

// optional .CSProtocol.CSMsgPkgLoginReq csMsgPkgLoginReq = 3;
inline bool CSMsgPkgBody::has_csmsgpkgloginreq() const {
  return !_is_default_instance_ && csmsgpkgloginreq_ != NULL;
}
inline void CSMsgPkgBody::clear_csmsgpkgloginreq() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgloginreq_ != NULL) delete csmsgpkgloginreq_;
  csmsgpkgloginreq_ = NULL;
}
inline const ::CSProtocol::CSMsgPkgLoginReq& CSMsgPkgBody::csmsgpkgloginreq() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
  return csmsgpkgloginreq_ != NULL ? *csmsgpkgloginreq_ : *default_instance_->csmsgpkgloginreq_;
}
inline ::CSProtocol::CSMsgPkgLoginReq* CSMsgPkgBody::mutable_csmsgpkgloginreq() {
  
  if (csmsgpkgloginreq_ == NULL) {
    csmsgpkgloginreq_ = new ::CSProtocol::CSMsgPkgLoginReq;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
  return csmsgpkgloginreq_;
}
inline ::CSProtocol::CSMsgPkgLoginReq* CSMsgPkgBody::release_csmsgpkgloginreq() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
  
  ::CSProtocol::CSMsgPkgLoginReq* temp = csmsgpkgloginreq_;
  csmsgpkgloginreq_ = NULL;
  return temp;
}
inline void CSMsgPkgBody::set_allocated_csmsgpkgloginreq(::CSProtocol::CSMsgPkgLoginReq* csmsgpkgloginreq) {
  delete csmsgpkgloginreq_;
  csmsgpkgloginreq_ = csmsgpkgloginreq;
  if (csmsgpkgloginreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
}

// optional .CSProtocol.CSMsgPkgLoginRsp csMsgPkgLoginRsp = 4;
inline bool CSMsgPkgBody::has_csmsgpkgloginrsp() const {
  return !_is_default_instance_ && csmsgpkgloginrsp_ != NULL;
}
inline void CSMsgPkgBody::clear_csmsgpkgloginrsp() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgloginrsp_ != NULL) delete csmsgpkgloginrsp_;
  csmsgpkgloginrsp_ = NULL;
}
inline const ::CSProtocol::CSMsgPkgLoginRsp& CSMsgPkgBody::csmsgpkgloginrsp() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
  return csmsgpkgloginrsp_ != NULL ? *csmsgpkgloginrsp_ : *default_instance_->csmsgpkgloginrsp_;
}
inline ::CSProtocol::CSMsgPkgLoginRsp* CSMsgPkgBody::mutable_csmsgpkgloginrsp() {
  
  if (csmsgpkgloginrsp_ == NULL) {
    csmsgpkgloginrsp_ = new ::CSProtocol::CSMsgPkgLoginRsp;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
  return csmsgpkgloginrsp_;
}
inline ::CSProtocol::CSMsgPkgLoginRsp* CSMsgPkgBody::release_csmsgpkgloginrsp() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
  
  ::CSProtocol::CSMsgPkgLoginRsp* temp = csmsgpkgloginrsp_;
  csmsgpkgloginrsp_ = NULL;
  return temp;
}
inline void CSMsgPkgBody::set_allocated_csmsgpkgloginrsp(::CSProtocol::CSMsgPkgLoginRsp* csmsgpkgloginrsp) {
  delete csmsgpkgloginrsp_;
  csmsgpkgloginrsp_ = csmsgpkgloginrsp;
  if (csmsgpkgloginrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
}

// optional .CSProtocol.CSMsgPkgRegisterReq csMsgPkgRegisterReq = 5;
inline bool CSMsgPkgBody::has_csmsgpkgregisterreq() const {
  return !_is_default_instance_ && csmsgpkgregisterreq_ != NULL;
}
inline void CSMsgPkgBody::clear_csmsgpkgregisterreq() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgregisterreq_ != NULL) delete csmsgpkgregisterreq_;
  csmsgpkgregisterreq_ = NULL;
}
inline const ::CSProtocol::CSMsgPkgRegisterReq& CSMsgPkgBody::csmsgpkgregisterreq() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
  return csmsgpkgregisterreq_ != NULL ? *csmsgpkgregisterreq_ : *default_instance_->csmsgpkgregisterreq_;
}
inline ::CSProtocol::CSMsgPkgRegisterReq* CSMsgPkgBody::mutable_csmsgpkgregisterreq() {
  
  if (csmsgpkgregisterreq_ == NULL) {
    csmsgpkgregisterreq_ = new ::CSProtocol::CSMsgPkgRegisterReq;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
  return csmsgpkgregisterreq_;
}
inline ::CSProtocol::CSMsgPkgRegisterReq* CSMsgPkgBody::release_csmsgpkgregisterreq() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
  
  ::CSProtocol::CSMsgPkgRegisterReq* temp = csmsgpkgregisterreq_;
  csmsgpkgregisterreq_ = NULL;
  return temp;
}
inline void CSMsgPkgBody::set_allocated_csmsgpkgregisterreq(::CSProtocol::CSMsgPkgRegisterReq* csmsgpkgregisterreq) {
  delete csmsgpkgregisterreq_;
  csmsgpkgregisterreq_ = csmsgpkgregisterreq;
  if (csmsgpkgregisterreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
}

// optional .CSProtocol.CSMsgPkgRegisterRsp csMsgPkgRegisterRsp = 6;
inline bool CSMsgPkgBody::has_csmsgpkgregisterrsp() const {
  return !_is_default_instance_ && csmsgpkgregisterrsp_ != NULL;
}
inline void CSMsgPkgBody::clear_csmsgpkgregisterrsp() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgregisterrsp_ != NULL) delete csmsgpkgregisterrsp_;
  csmsgpkgregisterrsp_ = NULL;
}
inline const ::CSProtocol::CSMsgPkgRegisterRsp& CSMsgPkgBody::csmsgpkgregisterrsp() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
  return csmsgpkgregisterrsp_ != NULL ? *csmsgpkgregisterrsp_ : *default_instance_->csmsgpkgregisterrsp_;
}
inline ::CSProtocol::CSMsgPkgRegisterRsp* CSMsgPkgBody::mutable_csmsgpkgregisterrsp() {
  
  if (csmsgpkgregisterrsp_ == NULL) {
    csmsgpkgregisterrsp_ = new ::CSProtocol::CSMsgPkgRegisterRsp;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
  return csmsgpkgregisterrsp_;
}
inline ::CSProtocol::CSMsgPkgRegisterRsp* CSMsgPkgBody::release_csmsgpkgregisterrsp() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
  
  ::CSProtocol::CSMsgPkgRegisterRsp* temp = csmsgpkgregisterrsp_;
  csmsgpkgregisterrsp_ = NULL;
  return temp;
}
inline void CSMsgPkgBody::set_allocated_csmsgpkgregisterrsp(::CSProtocol::CSMsgPkgRegisterRsp* csmsgpkgregisterrsp) {
  delete csmsgpkgregisterrsp_;
  csmsgpkgregisterrsp_ = csmsgpkgregisterrsp;
  if (csmsgpkgregisterrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CSProtocol

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::CSProtocol::CSMsgIDDef> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CSProtocol::CSMsgIDDef>() {
  return ::CSProtocol::CSMsgIDDef_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CSProtoPkgBodyDef_2eproto__INCLUDED
