// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CSProtoPkgBodyDef.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CSProtoPkgBodyDef.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace CSProtocol {

namespace {

const ::google::protobuf::Descriptor* CSMsgPkgHeartBeatReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgHeartBeatReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* CSMsgPkgHeartBeatRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgHeartBeatRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* CSMsgPkgLoginReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgLoginReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* CSMsgPkgLoginRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgLoginRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* CSMsgPkgRegisterReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgRegisterReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* CSMsgPkgRegisterRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgRegisterRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* CSMsgPkgBody_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgBody_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* CSMsgIDDef_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto() {
  protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CSProtoPkgBodyDef.proto");
  GOOGLE_CHECK(file != NULL);
  CSMsgPkgHeartBeatReq_descriptor_ = file->message_type(0);
  static const int CSMsgPkgHeartBeatReq_offsets_[1] = {
  };
  CSMsgPkgHeartBeatReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgHeartBeatReq_descriptor_,
      CSMsgPkgHeartBeatReq::default_instance_,
      CSMsgPkgHeartBeatReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgHeartBeatReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHeartBeatReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHeartBeatReq, _is_default_instance_));
  CSMsgPkgHeartBeatRsp_descriptor_ = file->message_type(1);
  static const int CSMsgPkgHeartBeatRsp_offsets_[1] = {
  };
  CSMsgPkgHeartBeatRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgHeartBeatRsp_descriptor_,
      CSMsgPkgHeartBeatRsp::default_instance_,
      CSMsgPkgHeartBeatRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgHeartBeatRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHeartBeatRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHeartBeatRsp, _is_default_instance_));
  CSMsgPkgLoginReq_descriptor_ = file->message_type(2);
  static const int CSMsgPkgLoginReq_offsets_[1] = {
  };
  CSMsgPkgLoginReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgLoginReq_descriptor_,
      CSMsgPkgLoginReq::default_instance_,
      CSMsgPkgLoginReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgLoginReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgLoginReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgLoginReq, _is_default_instance_));
  CSMsgPkgLoginRsp_descriptor_ = file->message_type(3);
  static const int CSMsgPkgLoginRsp_offsets_[1] = {
  };
  CSMsgPkgLoginRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgLoginRsp_descriptor_,
      CSMsgPkgLoginRsp::default_instance_,
      CSMsgPkgLoginRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgLoginRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgLoginRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgLoginRsp, _is_default_instance_));
  CSMsgPkgRegisterReq_descriptor_ = file->message_type(4);
  static const int CSMsgPkgRegisterReq_offsets_[1] = {
  };
  CSMsgPkgRegisterReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgRegisterReq_descriptor_,
      CSMsgPkgRegisterReq::default_instance_,
      CSMsgPkgRegisterReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgRegisterReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgRegisterReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgRegisterReq, _is_default_instance_));
  CSMsgPkgRegisterRsp_descriptor_ = file->message_type(5);
  static const int CSMsgPkgRegisterRsp_offsets_[1] = {
  };
  CSMsgPkgRegisterRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgRegisterRsp_descriptor_,
      CSMsgPkgRegisterRsp::default_instance_,
      CSMsgPkgRegisterRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgRegisterRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgRegisterRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgRegisterRsp, _is_default_instance_));
  CSMsgPkgBody_descriptor_ = file->message_type(6);
  static const int CSMsgPkgBody_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, csmsgpkgheartbeatreq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, csmsgpkgheartbeatrsp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, csmsgpkgloginreq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, csmsgpkgloginrsp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, csmsgpkgregisterreq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, csmsgpkgregisterrsp_),
  };
  CSMsgPkgBody_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgBody_descriptor_,
      CSMsgPkgBody::default_instance_,
      CSMsgPkgBody_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgBody),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgBody, _is_default_instance_));
  CSMsgIDDef_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CSProtoPkgBodyDef_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgHeartBeatReq_descriptor_, &CSMsgPkgHeartBeatReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgHeartBeatRsp_descriptor_, &CSMsgPkgHeartBeatRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgLoginReq_descriptor_, &CSMsgPkgLoginReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgLoginRsp_descriptor_, &CSMsgPkgLoginRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgRegisterReq_descriptor_, &CSMsgPkgRegisterReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgRegisterRsp_descriptor_, &CSMsgPkgRegisterRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgBody_descriptor_, &CSMsgPkgBody::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto() {
  delete CSMsgPkgHeartBeatReq::default_instance_;
  delete CSMsgPkgHeartBeatReq_reflection_;
  delete CSMsgPkgHeartBeatRsp::default_instance_;
  delete CSMsgPkgHeartBeatRsp_reflection_;
  delete CSMsgPkgLoginReq::default_instance_;
  delete CSMsgPkgLoginReq_reflection_;
  delete CSMsgPkgLoginRsp::default_instance_;
  delete CSMsgPkgLoginRsp_reflection_;
  delete CSMsgPkgRegisterReq::default_instance_;
  delete CSMsgPkgRegisterReq_reflection_;
  delete CSMsgPkgRegisterRsp::default_instance_;
  delete CSMsgPkgRegisterRsp_reflection_;
  delete CSMsgPkgBody::default_instance_;
  delete CSMsgPkgBody_reflection_;
}

void protobuf_AddDesc_CSProtoPkgBodyDef_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_CSProtoPkgBodyDef_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027CSProtoPkgBodyDef.proto\022\nCSProtocol\"\026\n"
    "\024CSMsgPkgHeartBeatReq\"\026\n\024CSMsgPkgHeartBe"
    "atRsp\"\022\n\020CSMsgPkgLoginReq\"\022\n\020CSMsgPkgLog"
    "inRsp\"\025\n\023CSMsgPkgRegisterReq\"\025\n\023CSMsgPkg"
    "RegisterRsp\"\372\002\n\014CSMsgPkgBody\022>\n\024csMsgPkg"
    "HeartBeatReq\030\001 \001(\0132 .CSProtocol.CSMsgPkg"
    "HeartBeatReq\022>\n\024csMsgPkgHeartBeatRsp\030\002 \001"
    "(\0132 .CSProtocol.CSMsgPkgHeartBeatRsp\0226\n\020"
    "csMsgPkgLoginReq\030\003 \001(\0132\034.CSProtocol.CSMs"
    "gPkgLoginReq\0226\n\020csMsgPkgLoginRsp\030\004 \001(\0132\034"
    ".CSProtocol.CSMsgPkgLoginRsp\022<\n\023csMsgPkg"
    "RegisterReq\030\005 \001(\0132\037.CSProtocol.CSMsgPkgR"
    "egisterReq\022<\n\023csMsgPkgRegisterRsp\030\006 \001(\0132"
    "\037.CSProtocol.CSMsgPkgRegisterRsp*\250\001\n\nCSM"
    "sgIDDef\022\016\n\nCSMsg_None\020\000\022\027\n\022CSMsg_HeartBe"
    "atReq\020\221N\022\027\n\022CSMsg_HeartBeatRsp\020\222N\022\023\n\016CSM"
    "sg_LoginReq\020\223N\022\023\n\016CSMsg_LoginRsp\020\224N\022\026\n\021C"
    "SMsg_RegisterReq\020\225N\022\026\n\021CSMsg_RegisterRsp"
    "\020\226Nb\006proto3", 731);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CSProtoPkgBodyDef.proto", &protobuf_RegisterTypes);
  CSMsgPkgHeartBeatReq::default_instance_ = new CSMsgPkgHeartBeatReq();
  CSMsgPkgHeartBeatRsp::default_instance_ = new CSMsgPkgHeartBeatRsp();
  CSMsgPkgLoginReq::default_instance_ = new CSMsgPkgLoginReq();
  CSMsgPkgLoginRsp::default_instance_ = new CSMsgPkgLoginRsp();
  CSMsgPkgRegisterReq::default_instance_ = new CSMsgPkgRegisterReq();
  CSMsgPkgRegisterRsp::default_instance_ = new CSMsgPkgRegisterRsp();
  CSMsgPkgBody::default_instance_ = new CSMsgPkgBody();
  CSMsgPkgHeartBeatReq::default_instance_->InitAsDefaultInstance();
  CSMsgPkgHeartBeatRsp::default_instance_->InitAsDefaultInstance();
  CSMsgPkgLoginReq::default_instance_->InitAsDefaultInstance();
  CSMsgPkgLoginRsp::default_instance_->InitAsDefaultInstance();
  CSMsgPkgRegisterReq::default_instance_->InitAsDefaultInstance();
  CSMsgPkgRegisterRsp::default_instance_->InitAsDefaultInstance();
  CSMsgPkgBody::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CSProtoPkgBodyDef_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CSProtoPkgBodyDef_2eproto {
  StaticDescriptorInitializer_CSProtoPkgBodyDef_2eproto() {
    protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  }
} static_descriptor_initializer_CSProtoPkgBodyDef_2eproto_;
const ::google::protobuf::EnumDescriptor* CSMsgIDDef_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgIDDef_descriptor_;
}
bool CSMsgIDDef_IsValid(int value) {
  switch(value) {
    case 0:
    case 10001:
    case 10002:
    case 10003:
    case 10004:
    case 10005:
    case 10006:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgHeartBeatReq::CSMsgPkgHeartBeatReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgHeartBeatReq)
}

void CSMsgPkgHeartBeatReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CSMsgPkgHeartBeatReq::CSMsgPkgHeartBeatReq(const CSMsgPkgHeartBeatReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgHeartBeatReq)
}

void CSMsgPkgHeartBeatReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CSMsgPkgHeartBeatReq::~CSMsgPkgHeartBeatReq() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgHeartBeatReq)
  SharedDtor();
}

void CSMsgPkgHeartBeatReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CSMsgPkgHeartBeatReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgHeartBeatReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgHeartBeatReq_descriptor_;
}

const CSMsgPkgHeartBeatReq& CSMsgPkgHeartBeatReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  return *default_instance_;
}

CSMsgPkgHeartBeatReq* CSMsgPkgHeartBeatReq::default_instance_ = NULL;

CSMsgPkgHeartBeatReq* CSMsgPkgHeartBeatReq::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgHeartBeatReq* n = new CSMsgPkgHeartBeatReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgHeartBeatReq::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgHeartBeatReq)
}

bool CSMsgPkgHeartBeatReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgHeartBeatReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgHeartBeatReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgHeartBeatReq)
  return false;
#undef DO_
}

void CSMsgPkgHeartBeatReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgHeartBeatReq)
  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgHeartBeatReq)
}

::google::protobuf::uint8* CSMsgPkgHeartBeatReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgHeartBeatReq)
  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgHeartBeatReq)
  return target;
}

int CSMsgPkgHeartBeatReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgHeartBeatReq)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgHeartBeatReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgHeartBeatReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgHeartBeatReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgHeartBeatReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgHeartBeatReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgHeartBeatReq)
    MergeFrom(*source);
  }
}

void CSMsgPkgHeartBeatReq::MergeFrom(const CSMsgPkgHeartBeatReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgHeartBeatReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void CSMsgPkgHeartBeatReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgHeartBeatReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgHeartBeatReq::CopyFrom(const CSMsgPkgHeartBeatReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgHeartBeatReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgHeartBeatReq::IsInitialized() const {

  return true;
}

void CSMsgPkgHeartBeatReq::Swap(CSMsgPkgHeartBeatReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgHeartBeatReq::InternalSwap(CSMsgPkgHeartBeatReq* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgHeartBeatReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgHeartBeatReq_descriptor_;
  metadata.reflection = CSMsgPkgHeartBeatReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgHeartBeatReq

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgHeartBeatRsp::CSMsgPkgHeartBeatRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgHeartBeatRsp)
}

void CSMsgPkgHeartBeatRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CSMsgPkgHeartBeatRsp::CSMsgPkgHeartBeatRsp(const CSMsgPkgHeartBeatRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgHeartBeatRsp)
}

void CSMsgPkgHeartBeatRsp::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CSMsgPkgHeartBeatRsp::~CSMsgPkgHeartBeatRsp() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgHeartBeatRsp)
  SharedDtor();
}

void CSMsgPkgHeartBeatRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CSMsgPkgHeartBeatRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgHeartBeatRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgHeartBeatRsp_descriptor_;
}

const CSMsgPkgHeartBeatRsp& CSMsgPkgHeartBeatRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  return *default_instance_;
}

CSMsgPkgHeartBeatRsp* CSMsgPkgHeartBeatRsp::default_instance_ = NULL;

CSMsgPkgHeartBeatRsp* CSMsgPkgHeartBeatRsp::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgHeartBeatRsp* n = new CSMsgPkgHeartBeatRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgHeartBeatRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgHeartBeatRsp)
}

bool CSMsgPkgHeartBeatRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgHeartBeatRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgHeartBeatRsp)
  return false;
#undef DO_
}

void CSMsgPkgHeartBeatRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgHeartBeatRsp)
}

::google::protobuf::uint8* CSMsgPkgHeartBeatRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgHeartBeatRsp)
  return target;
}

int CSMsgPkgHeartBeatRsp::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgHeartBeatRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgHeartBeatRsp* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgHeartBeatRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgHeartBeatRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgHeartBeatRsp)
    MergeFrom(*source);
  }
}

void CSMsgPkgHeartBeatRsp::MergeFrom(const CSMsgPkgHeartBeatRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void CSMsgPkgHeartBeatRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgHeartBeatRsp::CopyFrom(const CSMsgPkgHeartBeatRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgHeartBeatRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgHeartBeatRsp::IsInitialized() const {

  return true;
}

void CSMsgPkgHeartBeatRsp::Swap(CSMsgPkgHeartBeatRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgHeartBeatRsp::InternalSwap(CSMsgPkgHeartBeatRsp* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgHeartBeatRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgHeartBeatRsp_descriptor_;
  metadata.reflection = CSMsgPkgHeartBeatRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgHeartBeatRsp

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgLoginReq::CSMsgPkgLoginReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgLoginReq)
}

void CSMsgPkgLoginReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CSMsgPkgLoginReq::CSMsgPkgLoginReq(const CSMsgPkgLoginReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgLoginReq)
}

void CSMsgPkgLoginReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CSMsgPkgLoginReq::~CSMsgPkgLoginReq() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgLoginReq)
  SharedDtor();
}

void CSMsgPkgLoginReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CSMsgPkgLoginReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgLoginReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgLoginReq_descriptor_;
}

const CSMsgPkgLoginReq& CSMsgPkgLoginReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  return *default_instance_;
}

CSMsgPkgLoginReq* CSMsgPkgLoginReq::default_instance_ = NULL;

CSMsgPkgLoginReq* CSMsgPkgLoginReq::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgLoginReq* n = new CSMsgPkgLoginReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgLoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgLoginReq)
}

bool CSMsgPkgLoginReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgLoginReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgLoginReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgLoginReq)
  return false;
#undef DO_
}

void CSMsgPkgLoginReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgLoginReq)
  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgLoginReq)
}

::google::protobuf::uint8* CSMsgPkgLoginReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgLoginReq)
  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgLoginReq)
  return target;
}

int CSMsgPkgLoginReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgLoginReq)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgLoginReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgLoginReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgLoginReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgLoginReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgLoginReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgLoginReq)
    MergeFrom(*source);
  }
}

void CSMsgPkgLoginReq::MergeFrom(const CSMsgPkgLoginReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgLoginReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void CSMsgPkgLoginReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgLoginReq::CopyFrom(const CSMsgPkgLoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgLoginReq::IsInitialized() const {

  return true;
}

void CSMsgPkgLoginReq::Swap(CSMsgPkgLoginReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgLoginReq::InternalSwap(CSMsgPkgLoginReq* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgLoginReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgLoginReq_descriptor_;
  metadata.reflection = CSMsgPkgLoginReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgLoginReq

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgLoginRsp::CSMsgPkgLoginRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgLoginRsp)
}

void CSMsgPkgLoginRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CSMsgPkgLoginRsp::CSMsgPkgLoginRsp(const CSMsgPkgLoginRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgLoginRsp)
}

void CSMsgPkgLoginRsp::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CSMsgPkgLoginRsp::~CSMsgPkgLoginRsp() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgLoginRsp)
  SharedDtor();
}

void CSMsgPkgLoginRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CSMsgPkgLoginRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgLoginRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgLoginRsp_descriptor_;
}

const CSMsgPkgLoginRsp& CSMsgPkgLoginRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  return *default_instance_;
}

CSMsgPkgLoginRsp* CSMsgPkgLoginRsp::default_instance_ = NULL;

CSMsgPkgLoginRsp* CSMsgPkgLoginRsp::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgLoginRsp* n = new CSMsgPkgLoginRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgLoginRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgLoginRsp)
}

bool CSMsgPkgLoginRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgLoginRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgLoginRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgLoginRsp)
  return false;
#undef DO_
}

void CSMsgPkgLoginRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgLoginRsp)
  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgLoginRsp)
}

::google::protobuf::uint8* CSMsgPkgLoginRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgLoginRsp)
  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgLoginRsp)
  return target;
}

int CSMsgPkgLoginRsp::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgLoginRsp)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgLoginRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgLoginRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgLoginRsp* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgLoginRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgLoginRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgLoginRsp)
    MergeFrom(*source);
  }
}

void CSMsgPkgLoginRsp::MergeFrom(const CSMsgPkgLoginRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgLoginRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void CSMsgPkgLoginRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgLoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgLoginRsp::CopyFrom(const CSMsgPkgLoginRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgLoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgLoginRsp::IsInitialized() const {

  return true;
}

void CSMsgPkgLoginRsp::Swap(CSMsgPkgLoginRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgLoginRsp::InternalSwap(CSMsgPkgLoginRsp* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgLoginRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgLoginRsp_descriptor_;
  metadata.reflection = CSMsgPkgLoginRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgLoginRsp

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgRegisterReq::CSMsgPkgRegisterReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgRegisterReq)
}

void CSMsgPkgRegisterReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CSMsgPkgRegisterReq::CSMsgPkgRegisterReq(const CSMsgPkgRegisterReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgRegisterReq)
}

void CSMsgPkgRegisterReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CSMsgPkgRegisterReq::~CSMsgPkgRegisterReq() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgRegisterReq)
  SharedDtor();
}

void CSMsgPkgRegisterReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CSMsgPkgRegisterReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgRegisterReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgRegisterReq_descriptor_;
}

const CSMsgPkgRegisterReq& CSMsgPkgRegisterReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  return *default_instance_;
}

CSMsgPkgRegisterReq* CSMsgPkgRegisterReq::default_instance_ = NULL;

CSMsgPkgRegisterReq* CSMsgPkgRegisterReq::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgRegisterReq* n = new CSMsgPkgRegisterReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgRegisterReq::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgRegisterReq)
}

bool CSMsgPkgRegisterReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgRegisterReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgRegisterReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgRegisterReq)
  return false;
#undef DO_
}

void CSMsgPkgRegisterReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgRegisterReq)
  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgRegisterReq)
}

::google::protobuf::uint8* CSMsgPkgRegisterReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgRegisterReq)
  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgRegisterReq)
  return target;
}

int CSMsgPkgRegisterReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgRegisterReq)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgRegisterReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgRegisterReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgRegisterReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgRegisterReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgRegisterReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgRegisterReq)
    MergeFrom(*source);
  }
}

void CSMsgPkgRegisterReq::MergeFrom(const CSMsgPkgRegisterReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgRegisterReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void CSMsgPkgRegisterReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgRegisterReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgRegisterReq::CopyFrom(const CSMsgPkgRegisterReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgRegisterReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgRegisterReq::IsInitialized() const {

  return true;
}

void CSMsgPkgRegisterReq::Swap(CSMsgPkgRegisterReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgRegisterReq::InternalSwap(CSMsgPkgRegisterReq* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgRegisterReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgRegisterReq_descriptor_;
  metadata.reflection = CSMsgPkgRegisterReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgRegisterReq

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgRegisterRsp::CSMsgPkgRegisterRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgRegisterRsp)
}

void CSMsgPkgRegisterRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CSMsgPkgRegisterRsp::CSMsgPkgRegisterRsp(const CSMsgPkgRegisterRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgRegisterRsp)
}

void CSMsgPkgRegisterRsp::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CSMsgPkgRegisterRsp::~CSMsgPkgRegisterRsp() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgRegisterRsp)
  SharedDtor();
}

void CSMsgPkgRegisterRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CSMsgPkgRegisterRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgRegisterRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgRegisterRsp_descriptor_;
}

const CSMsgPkgRegisterRsp& CSMsgPkgRegisterRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  return *default_instance_;
}

CSMsgPkgRegisterRsp* CSMsgPkgRegisterRsp::default_instance_ = NULL;

CSMsgPkgRegisterRsp* CSMsgPkgRegisterRsp::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgRegisterRsp* n = new CSMsgPkgRegisterRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgRegisterRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgRegisterRsp)
}

bool CSMsgPkgRegisterRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgRegisterRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgRegisterRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgRegisterRsp)
  return false;
#undef DO_
}

void CSMsgPkgRegisterRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgRegisterRsp)
  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgRegisterRsp)
}

::google::protobuf::uint8* CSMsgPkgRegisterRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgRegisterRsp)
  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgRegisterRsp)
  return target;
}

int CSMsgPkgRegisterRsp::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgRegisterRsp)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgRegisterRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgRegisterRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgRegisterRsp* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgRegisterRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgRegisterRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgRegisterRsp)
    MergeFrom(*source);
  }
}

void CSMsgPkgRegisterRsp::MergeFrom(const CSMsgPkgRegisterRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgRegisterRsp)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void CSMsgPkgRegisterRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgRegisterRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgRegisterRsp::CopyFrom(const CSMsgPkgRegisterRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgRegisterRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgRegisterRsp::IsInitialized() const {

  return true;
}

void CSMsgPkgRegisterRsp::Swap(CSMsgPkgRegisterRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgRegisterRsp::InternalSwap(CSMsgPkgRegisterRsp* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgRegisterRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgRegisterRsp_descriptor_;
  metadata.reflection = CSMsgPkgRegisterRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgRegisterRsp

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CSMsgPkgBody::kCsMsgPkgHeartBeatReqFieldNumber;
const int CSMsgPkgBody::kCsMsgPkgHeartBeatRspFieldNumber;
const int CSMsgPkgBody::kCsMsgPkgLoginReqFieldNumber;
const int CSMsgPkgBody::kCsMsgPkgLoginRspFieldNumber;
const int CSMsgPkgBody::kCsMsgPkgRegisterReqFieldNumber;
const int CSMsgPkgBody::kCsMsgPkgRegisterRspFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgBody::CSMsgPkgBody()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgBody)
}

void CSMsgPkgBody::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  csmsgpkgheartbeatreq_ = const_cast< ::CSProtocol::CSMsgPkgHeartBeatReq*>(&::CSProtocol::CSMsgPkgHeartBeatReq::default_instance());
  csmsgpkgheartbeatrsp_ = const_cast< ::CSProtocol::CSMsgPkgHeartBeatRsp*>(&::CSProtocol::CSMsgPkgHeartBeatRsp::default_instance());
  csmsgpkgloginreq_ = const_cast< ::CSProtocol::CSMsgPkgLoginReq*>(&::CSProtocol::CSMsgPkgLoginReq::default_instance());
  csmsgpkgloginrsp_ = const_cast< ::CSProtocol::CSMsgPkgLoginRsp*>(&::CSProtocol::CSMsgPkgLoginRsp::default_instance());
  csmsgpkgregisterreq_ = const_cast< ::CSProtocol::CSMsgPkgRegisterReq*>(&::CSProtocol::CSMsgPkgRegisterReq::default_instance());
  csmsgpkgregisterrsp_ = const_cast< ::CSProtocol::CSMsgPkgRegisterRsp*>(&::CSProtocol::CSMsgPkgRegisterRsp::default_instance());
}

CSMsgPkgBody::CSMsgPkgBody(const CSMsgPkgBody& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgBody)
}

void CSMsgPkgBody::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  csmsgpkgheartbeatreq_ = NULL;
  csmsgpkgheartbeatrsp_ = NULL;
  csmsgpkgloginreq_ = NULL;
  csmsgpkgloginrsp_ = NULL;
  csmsgpkgregisterreq_ = NULL;
  csmsgpkgregisterrsp_ = NULL;
}

CSMsgPkgBody::~CSMsgPkgBody() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgBody)
  SharedDtor();
}

void CSMsgPkgBody::SharedDtor() {
  if (this != default_instance_) {
    delete csmsgpkgheartbeatreq_;
    delete csmsgpkgheartbeatrsp_;
    delete csmsgpkgloginreq_;
    delete csmsgpkgloginrsp_;
    delete csmsgpkgregisterreq_;
    delete csmsgpkgregisterrsp_;
  }
}

void CSMsgPkgBody::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgBody::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgBody_descriptor_;
}

const CSMsgPkgBody& CSMsgPkgBody::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  return *default_instance_;
}

CSMsgPkgBody* CSMsgPkgBody::default_instance_ = NULL;

CSMsgPkgBody* CSMsgPkgBody::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgBody* n = new CSMsgPkgBody;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgBody::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgBody)
  if (GetArenaNoVirtual() == NULL && csmsgpkgheartbeatreq_ != NULL) delete csmsgpkgheartbeatreq_;
  csmsgpkgheartbeatreq_ = NULL;
  if (GetArenaNoVirtual() == NULL && csmsgpkgheartbeatrsp_ != NULL) delete csmsgpkgheartbeatrsp_;
  csmsgpkgheartbeatrsp_ = NULL;
  if (GetArenaNoVirtual() == NULL && csmsgpkgloginreq_ != NULL) delete csmsgpkgloginreq_;
  csmsgpkgloginreq_ = NULL;
  if (GetArenaNoVirtual() == NULL && csmsgpkgloginrsp_ != NULL) delete csmsgpkgloginrsp_;
  csmsgpkgloginrsp_ = NULL;
  if (GetArenaNoVirtual() == NULL && csmsgpkgregisterreq_ != NULL) delete csmsgpkgregisterreq_;
  csmsgpkgregisterreq_ = NULL;
  if (GetArenaNoVirtual() == NULL && csmsgpkgregisterrsp_ != NULL) delete csmsgpkgregisterrsp_;
  csmsgpkgregisterrsp_ = NULL;
}

bool CSMsgPkgBody::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgBody)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CSProtocol.CSMsgPkgHeartBeatReq csMsgPkgHeartBeatReq = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkgheartbeatreq()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_csMsgPkgHeartBeatRsp;
        break;
      }

      // optional .CSProtocol.CSMsgPkgHeartBeatRsp csMsgPkgHeartBeatRsp = 2;
      case 2: {
        if (tag == 18) {
         parse_csMsgPkgHeartBeatRsp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkgheartbeatrsp()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_csMsgPkgLoginReq;
        break;
      }

      // optional .CSProtocol.CSMsgPkgLoginReq csMsgPkgLoginReq = 3;
      case 3: {
        if (tag == 26) {
         parse_csMsgPkgLoginReq:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkgloginreq()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_csMsgPkgLoginRsp;
        break;
      }

      // optional .CSProtocol.CSMsgPkgLoginRsp csMsgPkgLoginRsp = 4;
      case 4: {
        if (tag == 34) {
         parse_csMsgPkgLoginRsp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkgloginrsp()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_csMsgPkgRegisterReq;
        break;
      }

      // optional .CSProtocol.CSMsgPkgRegisterReq csMsgPkgRegisterReq = 5;
      case 5: {
        if (tag == 42) {
         parse_csMsgPkgRegisterReq:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkgregisterreq()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_csMsgPkgRegisterRsp;
        break;
      }

      // optional .CSProtocol.CSMsgPkgRegisterRsp csMsgPkgRegisterRsp = 6;
      case 6: {
        if (tag == 50) {
         parse_csMsgPkgRegisterRsp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkgregisterrsp()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgBody)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgBody)
  return false;
#undef DO_
}

void CSMsgPkgBody::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgBody)
  // optional .CSProtocol.CSMsgPkgHeartBeatReq csMsgPkgHeartBeatReq = 1;
  if (this->has_csmsgpkgheartbeatreq()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->csmsgpkgheartbeatreq_, output);
  }

  // optional .CSProtocol.CSMsgPkgHeartBeatRsp csMsgPkgHeartBeatRsp = 2;
  if (this->has_csmsgpkgheartbeatrsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->csmsgpkgheartbeatrsp_, output);
  }

  // optional .CSProtocol.CSMsgPkgLoginReq csMsgPkgLoginReq = 3;
  if (this->has_csmsgpkgloginreq()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->csmsgpkgloginreq_, output);
  }

  // optional .CSProtocol.CSMsgPkgLoginRsp csMsgPkgLoginRsp = 4;
  if (this->has_csmsgpkgloginrsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->csmsgpkgloginrsp_, output);
  }

  // optional .CSProtocol.CSMsgPkgRegisterReq csMsgPkgRegisterReq = 5;
  if (this->has_csmsgpkgregisterreq()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->csmsgpkgregisterreq_, output);
  }

  // optional .CSProtocol.CSMsgPkgRegisterRsp csMsgPkgRegisterRsp = 6;
  if (this->has_csmsgpkgregisterrsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->csmsgpkgregisterrsp_, output);
  }

  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgBody)
}

::google::protobuf::uint8* CSMsgPkgBody::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgBody)
  // optional .CSProtocol.CSMsgPkgHeartBeatReq csMsgPkgHeartBeatReq = 1;
  if (this->has_csmsgpkgheartbeatreq()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->csmsgpkgheartbeatreq_, false, target);
  }

  // optional .CSProtocol.CSMsgPkgHeartBeatRsp csMsgPkgHeartBeatRsp = 2;
  if (this->has_csmsgpkgheartbeatrsp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->csmsgpkgheartbeatrsp_, false, target);
  }

  // optional .CSProtocol.CSMsgPkgLoginReq csMsgPkgLoginReq = 3;
  if (this->has_csmsgpkgloginreq()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->csmsgpkgloginreq_, false, target);
  }

  // optional .CSProtocol.CSMsgPkgLoginRsp csMsgPkgLoginRsp = 4;
  if (this->has_csmsgpkgloginrsp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->csmsgpkgloginrsp_, false, target);
  }

  // optional .CSProtocol.CSMsgPkgRegisterReq csMsgPkgRegisterReq = 5;
  if (this->has_csmsgpkgregisterreq()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->csmsgpkgregisterreq_, false, target);
  }

  // optional .CSProtocol.CSMsgPkgRegisterRsp csMsgPkgRegisterRsp = 6;
  if (this->has_csmsgpkgregisterrsp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, *this->csmsgpkgregisterrsp_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgBody)
  return target;
}

int CSMsgPkgBody::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgBody)
  int total_size = 0;

  // optional .CSProtocol.CSMsgPkgHeartBeatReq csMsgPkgHeartBeatReq = 1;
  if (this->has_csmsgpkgheartbeatreq()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkgheartbeatreq_);
  }

  // optional .CSProtocol.CSMsgPkgHeartBeatRsp csMsgPkgHeartBeatRsp = 2;
  if (this->has_csmsgpkgheartbeatrsp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkgheartbeatrsp_);
  }

  // optional .CSProtocol.CSMsgPkgLoginReq csMsgPkgLoginReq = 3;
  if (this->has_csmsgpkgloginreq()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkgloginreq_);
  }

  // optional .CSProtocol.CSMsgPkgLoginRsp csMsgPkgLoginRsp = 4;
  if (this->has_csmsgpkgloginrsp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkgloginrsp_);
  }

  // optional .CSProtocol.CSMsgPkgRegisterReq csMsgPkgRegisterReq = 5;
  if (this->has_csmsgpkgregisterreq()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkgregisterreq_);
  }

  // optional .CSProtocol.CSMsgPkgRegisterRsp csMsgPkgRegisterRsp = 6;
  if (this->has_csmsgpkgregisterrsp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkgregisterrsp_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgBody::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgBody)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgBody* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgBody>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgBody)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgBody)
    MergeFrom(*source);
  }
}

void CSMsgPkgBody::MergeFrom(const CSMsgPkgBody& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgBody)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_csmsgpkgheartbeatreq()) {
    mutable_csmsgpkgheartbeatreq()->::CSProtocol::CSMsgPkgHeartBeatReq::MergeFrom(from.csmsgpkgheartbeatreq());
  }
  if (from.has_csmsgpkgheartbeatrsp()) {
    mutable_csmsgpkgheartbeatrsp()->::CSProtocol::CSMsgPkgHeartBeatRsp::MergeFrom(from.csmsgpkgheartbeatrsp());
  }
  if (from.has_csmsgpkgloginreq()) {
    mutable_csmsgpkgloginreq()->::CSProtocol::CSMsgPkgLoginReq::MergeFrom(from.csmsgpkgloginreq());
  }
  if (from.has_csmsgpkgloginrsp()) {
    mutable_csmsgpkgloginrsp()->::CSProtocol::CSMsgPkgLoginRsp::MergeFrom(from.csmsgpkgloginrsp());
  }
  if (from.has_csmsgpkgregisterreq()) {
    mutable_csmsgpkgregisterreq()->::CSProtocol::CSMsgPkgRegisterReq::MergeFrom(from.csmsgpkgregisterreq());
  }
  if (from.has_csmsgpkgregisterrsp()) {
    mutable_csmsgpkgregisterrsp()->::CSProtocol::CSMsgPkgRegisterRsp::MergeFrom(from.csmsgpkgregisterrsp());
  }
}

void CSMsgPkgBody::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgBody::CopyFrom(const CSMsgPkgBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgBody::IsInitialized() const {

  return true;
}

void CSMsgPkgBody::Swap(CSMsgPkgBody* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgBody::InternalSwap(CSMsgPkgBody* other) {
  std::swap(csmsgpkgheartbeatreq_, other->csmsgpkgheartbeatreq_);
  std::swap(csmsgpkgheartbeatrsp_, other->csmsgpkgheartbeatrsp_);
  std::swap(csmsgpkgloginreq_, other->csmsgpkgloginreq_);
  std::swap(csmsgpkgloginrsp_, other->csmsgpkgloginrsp_);
  std::swap(csmsgpkgregisterreq_, other->csmsgpkgregisterreq_);
  std::swap(csmsgpkgregisterrsp_, other->csmsgpkgregisterrsp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgBody::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgBody_descriptor_;
  metadata.reflection = CSMsgPkgBody_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgBody

// optional .CSProtocol.CSMsgPkgHeartBeatReq csMsgPkgHeartBeatReq = 1;
bool CSMsgPkgBody::has_csmsgpkgheartbeatreq() const {
  return !_is_default_instance_ && csmsgpkgheartbeatreq_ != NULL;
}
void CSMsgPkgBody::clear_csmsgpkgheartbeatreq() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgheartbeatreq_ != NULL) delete csmsgpkgheartbeatreq_;
  csmsgpkgheartbeatreq_ = NULL;
}
const ::CSProtocol::CSMsgPkgHeartBeatReq& CSMsgPkgBody::csmsgpkgheartbeatreq() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
  return csmsgpkgheartbeatreq_ != NULL ? *csmsgpkgheartbeatreq_ : *default_instance_->csmsgpkgheartbeatreq_;
}
::CSProtocol::CSMsgPkgHeartBeatReq* CSMsgPkgBody::mutable_csmsgpkgheartbeatreq() {
  
  if (csmsgpkgheartbeatreq_ == NULL) {
    csmsgpkgheartbeatreq_ = new ::CSProtocol::CSMsgPkgHeartBeatReq;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
  return csmsgpkgheartbeatreq_;
}
::CSProtocol::CSMsgPkgHeartBeatReq* CSMsgPkgBody::release_csmsgpkgheartbeatreq() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
  
  ::CSProtocol::CSMsgPkgHeartBeatReq* temp = csmsgpkgheartbeatreq_;
  csmsgpkgheartbeatreq_ = NULL;
  return temp;
}
void CSMsgPkgBody::set_allocated_csmsgpkgheartbeatreq(::CSProtocol::CSMsgPkgHeartBeatReq* csmsgpkgheartbeatreq) {
  delete csmsgpkgheartbeatreq_;
  csmsgpkgheartbeatreq_ = csmsgpkgheartbeatreq;
  if (csmsgpkgheartbeatreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatReq)
}

// optional .CSProtocol.CSMsgPkgHeartBeatRsp csMsgPkgHeartBeatRsp = 2;
bool CSMsgPkgBody::has_csmsgpkgheartbeatrsp() const {
  return !_is_default_instance_ && csmsgpkgheartbeatrsp_ != NULL;
}
void CSMsgPkgBody::clear_csmsgpkgheartbeatrsp() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgheartbeatrsp_ != NULL) delete csmsgpkgheartbeatrsp_;
  csmsgpkgheartbeatrsp_ = NULL;
}
const ::CSProtocol::CSMsgPkgHeartBeatRsp& CSMsgPkgBody::csmsgpkgheartbeatrsp() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
  return csmsgpkgheartbeatrsp_ != NULL ? *csmsgpkgheartbeatrsp_ : *default_instance_->csmsgpkgheartbeatrsp_;
}
::CSProtocol::CSMsgPkgHeartBeatRsp* CSMsgPkgBody::mutable_csmsgpkgheartbeatrsp() {
  
  if (csmsgpkgheartbeatrsp_ == NULL) {
    csmsgpkgheartbeatrsp_ = new ::CSProtocol::CSMsgPkgHeartBeatRsp;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
  return csmsgpkgheartbeatrsp_;
}
::CSProtocol::CSMsgPkgHeartBeatRsp* CSMsgPkgBody::release_csmsgpkgheartbeatrsp() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
  
  ::CSProtocol::CSMsgPkgHeartBeatRsp* temp = csmsgpkgheartbeatrsp_;
  csmsgpkgheartbeatrsp_ = NULL;
  return temp;
}
void CSMsgPkgBody::set_allocated_csmsgpkgheartbeatrsp(::CSProtocol::CSMsgPkgHeartBeatRsp* csmsgpkgheartbeatrsp) {
  delete csmsgpkgheartbeatrsp_;
  csmsgpkgheartbeatrsp_ = csmsgpkgheartbeatrsp;
  if (csmsgpkgheartbeatrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgHeartBeatRsp)
}

// optional .CSProtocol.CSMsgPkgLoginReq csMsgPkgLoginReq = 3;
bool CSMsgPkgBody::has_csmsgpkgloginreq() const {
  return !_is_default_instance_ && csmsgpkgloginreq_ != NULL;
}
void CSMsgPkgBody::clear_csmsgpkgloginreq() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgloginreq_ != NULL) delete csmsgpkgloginreq_;
  csmsgpkgloginreq_ = NULL;
}
const ::CSProtocol::CSMsgPkgLoginReq& CSMsgPkgBody::csmsgpkgloginreq() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
  return csmsgpkgloginreq_ != NULL ? *csmsgpkgloginreq_ : *default_instance_->csmsgpkgloginreq_;
}
::CSProtocol::CSMsgPkgLoginReq* CSMsgPkgBody::mutable_csmsgpkgloginreq() {
  
  if (csmsgpkgloginreq_ == NULL) {
    csmsgpkgloginreq_ = new ::CSProtocol::CSMsgPkgLoginReq;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
  return csmsgpkgloginreq_;
}
::CSProtocol::CSMsgPkgLoginReq* CSMsgPkgBody::release_csmsgpkgloginreq() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
  
  ::CSProtocol::CSMsgPkgLoginReq* temp = csmsgpkgloginreq_;
  csmsgpkgloginreq_ = NULL;
  return temp;
}
void CSMsgPkgBody::set_allocated_csmsgpkgloginreq(::CSProtocol::CSMsgPkgLoginReq* csmsgpkgloginreq) {
  delete csmsgpkgloginreq_;
  csmsgpkgloginreq_ = csmsgpkgloginreq;
  if (csmsgpkgloginreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgLoginReq)
}

// optional .CSProtocol.CSMsgPkgLoginRsp csMsgPkgLoginRsp = 4;
bool CSMsgPkgBody::has_csmsgpkgloginrsp() const {
  return !_is_default_instance_ && csmsgpkgloginrsp_ != NULL;
}
void CSMsgPkgBody::clear_csmsgpkgloginrsp() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgloginrsp_ != NULL) delete csmsgpkgloginrsp_;
  csmsgpkgloginrsp_ = NULL;
}
const ::CSProtocol::CSMsgPkgLoginRsp& CSMsgPkgBody::csmsgpkgloginrsp() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
  return csmsgpkgloginrsp_ != NULL ? *csmsgpkgloginrsp_ : *default_instance_->csmsgpkgloginrsp_;
}
::CSProtocol::CSMsgPkgLoginRsp* CSMsgPkgBody::mutable_csmsgpkgloginrsp() {
  
  if (csmsgpkgloginrsp_ == NULL) {
    csmsgpkgloginrsp_ = new ::CSProtocol::CSMsgPkgLoginRsp;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
  return csmsgpkgloginrsp_;
}
::CSProtocol::CSMsgPkgLoginRsp* CSMsgPkgBody::release_csmsgpkgloginrsp() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
  
  ::CSProtocol::CSMsgPkgLoginRsp* temp = csmsgpkgloginrsp_;
  csmsgpkgloginrsp_ = NULL;
  return temp;
}
void CSMsgPkgBody::set_allocated_csmsgpkgloginrsp(::CSProtocol::CSMsgPkgLoginRsp* csmsgpkgloginrsp) {
  delete csmsgpkgloginrsp_;
  csmsgpkgloginrsp_ = csmsgpkgloginrsp;
  if (csmsgpkgloginrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgLoginRsp)
}

// optional .CSProtocol.CSMsgPkgRegisterReq csMsgPkgRegisterReq = 5;
bool CSMsgPkgBody::has_csmsgpkgregisterreq() const {
  return !_is_default_instance_ && csmsgpkgregisterreq_ != NULL;
}
void CSMsgPkgBody::clear_csmsgpkgregisterreq() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgregisterreq_ != NULL) delete csmsgpkgregisterreq_;
  csmsgpkgregisterreq_ = NULL;
}
const ::CSProtocol::CSMsgPkgRegisterReq& CSMsgPkgBody::csmsgpkgregisterreq() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
  return csmsgpkgregisterreq_ != NULL ? *csmsgpkgregisterreq_ : *default_instance_->csmsgpkgregisterreq_;
}
::CSProtocol::CSMsgPkgRegisterReq* CSMsgPkgBody::mutable_csmsgpkgregisterreq() {
  
  if (csmsgpkgregisterreq_ == NULL) {
    csmsgpkgregisterreq_ = new ::CSProtocol::CSMsgPkgRegisterReq;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
  return csmsgpkgregisterreq_;
}
::CSProtocol::CSMsgPkgRegisterReq* CSMsgPkgBody::release_csmsgpkgregisterreq() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
  
  ::CSProtocol::CSMsgPkgRegisterReq* temp = csmsgpkgregisterreq_;
  csmsgpkgregisterreq_ = NULL;
  return temp;
}
void CSMsgPkgBody::set_allocated_csmsgpkgregisterreq(::CSProtocol::CSMsgPkgRegisterReq* csmsgpkgregisterreq) {
  delete csmsgpkgregisterreq_;
  csmsgpkgregisterreq_ = csmsgpkgregisterreq;
  if (csmsgpkgregisterreq) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterReq)
}

// optional .CSProtocol.CSMsgPkgRegisterRsp csMsgPkgRegisterRsp = 6;
bool CSMsgPkgBody::has_csmsgpkgregisterrsp() const {
  return !_is_default_instance_ && csmsgpkgregisterrsp_ != NULL;
}
void CSMsgPkgBody::clear_csmsgpkgregisterrsp() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgregisterrsp_ != NULL) delete csmsgpkgregisterrsp_;
  csmsgpkgregisterrsp_ = NULL;
}
const ::CSProtocol::CSMsgPkgRegisterRsp& CSMsgPkgBody::csmsgpkgregisterrsp() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
  return csmsgpkgregisterrsp_ != NULL ? *csmsgpkgregisterrsp_ : *default_instance_->csmsgpkgregisterrsp_;
}
::CSProtocol::CSMsgPkgRegisterRsp* CSMsgPkgBody::mutable_csmsgpkgregisterrsp() {
  
  if (csmsgpkgregisterrsp_ == NULL) {
    csmsgpkgregisterrsp_ = new ::CSProtocol::CSMsgPkgRegisterRsp;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
  return csmsgpkgregisterrsp_;
}
::CSProtocol::CSMsgPkgRegisterRsp* CSMsgPkgBody::release_csmsgpkgregisterrsp() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
  
  ::CSProtocol::CSMsgPkgRegisterRsp* temp = csmsgpkgregisterrsp_;
  csmsgpkgregisterrsp_ = NULL;
  return temp;
}
void CSMsgPkgBody::set_allocated_csmsgpkgregisterrsp(::CSProtocol::CSMsgPkgRegisterRsp* csmsgpkgregisterrsp) {
  delete csmsgpkgregisterrsp_;
  csmsgpkgregisterrsp_ = csmsgpkgregisterrsp;
  if (csmsgpkgregisterrsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgBody.csMsgPkgRegisterRsp)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace CSProtocol

// @@protoc_insertion_point(global_scope)
