// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CSProtoPkgDef.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CSProtoPkgDef.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace CSProtocol {

namespace {

const ::google::protobuf::Descriptor* CSMsgPkgHead_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkgHead_reflection_ = NULL;
const ::google::protobuf::Descriptor* CSMsgPkg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CSMsgPkg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CSProtoPkgDef_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_CSProtoPkgDef_2eproto() {
  protobuf_AddDesc_CSProtoPkgDef_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CSProtoPkgDef.proto");
  GOOGLE_CHECK(file != NULL);
  CSMsgPkgHead_descriptor_ = file->message_type(0);
  static const int CSMsgPkgHead_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHead, msgid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHead, pkgbodylen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHead, checksum_),
  };
  CSMsgPkgHead_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkgHead_descriptor_,
      CSMsgPkgHead::default_instance_,
      CSMsgPkgHead_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkgHead),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHead, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkgHead, _is_default_instance_));
  CSMsgPkg_descriptor_ = file->message_type(1);
  static const int CSMsgPkg_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkg, csmsgpkghead_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkg, csmsgpkgbody_),
  };
  CSMsgPkg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CSMsgPkg_descriptor_,
      CSMsgPkg::default_instance_,
      CSMsgPkg_offsets_,
      -1,
      -1,
      -1,
      sizeof(CSMsgPkg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkg, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CSMsgPkg, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CSProtoPkgDef_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkgHead_descriptor_, &CSMsgPkgHead::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CSMsgPkg_descriptor_, &CSMsgPkg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CSProtoPkgDef_2eproto() {
  delete CSMsgPkgHead::default_instance_;
  delete CSMsgPkgHead_reflection_;
  delete CSMsgPkg::default_instance_;
  delete CSMsgPkg_reflection_;
}

void protobuf_AddDesc_CSProtoPkgDef_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_CSProtoPkgDef_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::CSProtocol::protobuf_AddDesc_CSProtoPkgBodyDef_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023CSProtoPkgDef.proto\022\nCSProtocol\032\027CSPro"
    "toPkgBodyDef.proto\"C\n\014CSMsgPkgHead\022\r\n\005ms"
    "gID\030\001 \001(\r\022\022\n\npkgBodyLen\030\002 \001(\r\022\020\n\010checkSu"
    "m\030\003 \001(\t\"j\n\010CSMsgPkg\022.\n\014csMsgPkgHead\030\001 \001("
    "\0132\030.CSProtocol.CSMsgPkgHead\022.\n\014csMsgPkgB"
    "ody\030\002 \001(\0132\030.CSProtocol.CSMsgPkgBodyP\000b\006p"
    "roto3", 245);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CSProtoPkgDef.proto", &protobuf_RegisterTypes);
  CSMsgPkgHead::default_instance_ = new CSMsgPkgHead();
  CSMsgPkg::default_instance_ = new CSMsgPkg();
  CSMsgPkgHead::default_instance_->InitAsDefaultInstance();
  CSMsgPkg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CSProtoPkgDef_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CSProtoPkgDef_2eproto {
  StaticDescriptorInitializer_CSProtoPkgDef_2eproto() {
    protobuf_AddDesc_CSProtoPkgDef_2eproto();
  }
} static_descriptor_initializer_CSProtoPkgDef_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CSMsgPkgHead::kMsgIDFieldNumber;
const int CSMsgPkgHead::kPkgBodyLenFieldNumber;
const int CSMsgPkgHead::kCheckSumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkgHead::CSMsgPkgHead()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkgHead)
}

void CSMsgPkgHead::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CSMsgPkgHead::CSMsgPkgHead(const CSMsgPkgHead& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkgHead)
}

void CSMsgPkgHead::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  msgid_ = 0u;
  pkgbodylen_ = 0u;
  checksum_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CSMsgPkgHead::~CSMsgPkgHead() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkgHead)
  SharedDtor();
}

void CSMsgPkgHead::SharedDtor() {
  checksum_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void CSMsgPkgHead::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkgHead::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkgHead_descriptor_;
}

const CSMsgPkgHead& CSMsgPkgHead::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgDef_2eproto();
  return *default_instance_;
}

CSMsgPkgHead* CSMsgPkgHead::default_instance_ = NULL;

CSMsgPkgHead* CSMsgPkgHead::New(::google::protobuf::Arena* arena) const {
  CSMsgPkgHead* n = new CSMsgPkgHead;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkgHead::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkgHead)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(CSMsgPkgHead, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CSMsgPkgHead*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(msgid_, pkgbodylen_);
  checksum_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool CSMsgPkgHead::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkgHead)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 msgID = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &msgid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_pkgBodyLen;
        break;
      }

      // optional uint32 pkgBodyLen = 2;
      case 2: {
        if (tag == 16) {
         parse_pkgBodyLen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pkgbodylen_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_checkSum;
        break;
      }

      // optional string checkSum = 3;
      case 3: {
        if (tag == 26) {
         parse_checkSum:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_checksum()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->checksum().data(), this->checksum().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CSProtocol.CSMsgPkgHead.checkSum"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkgHead)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkgHead)
  return false;
#undef DO_
}

void CSMsgPkgHead::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkgHead)
  // optional uint32 msgID = 1;
  if (this->msgid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->msgid(), output);
  }

  // optional uint32 pkgBodyLen = 2;
  if (this->pkgbodylen() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->pkgbodylen(), output);
  }

  // optional string checkSum = 3;
  if (this->checksum().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->checksum().data(), this->checksum().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CSProtocol.CSMsgPkgHead.checkSum");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->checksum(), output);
  }

  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkgHead)
}

::google::protobuf::uint8* CSMsgPkgHead::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkgHead)
  // optional uint32 msgID = 1;
  if (this->msgid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->msgid(), target);
  }

  // optional uint32 pkgBodyLen = 2;
  if (this->pkgbodylen() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->pkgbodylen(), target);
  }

  // optional string checkSum = 3;
  if (this->checksum().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->checksum().data(), this->checksum().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CSProtocol.CSMsgPkgHead.checkSum");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->checksum(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkgHead)
  return target;
}

int CSMsgPkgHead::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkgHead)
  int total_size = 0;

  // optional uint32 msgID = 1;
  if (this->msgid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->msgid());
  }

  // optional uint32 pkgBodyLen = 2;
  if (this->pkgbodylen() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->pkgbodylen());
  }

  // optional string checkSum = 3;
  if (this->checksum().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->checksum());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkgHead::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkgHead)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkgHead* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkgHead>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkgHead)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkgHead)
    MergeFrom(*source);
  }
}

void CSMsgPkgHead::MergeFrom(const CSMsgPkgHead& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkgHead)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.msgid() != 0) {
    set_msgid(from.msgid());
  }
  if (from.pkgbodylen() != 0) {
    set_pkgbodylen(from.pkgbodylen());
  }
  if (from.checksum().size() > 0) {

    checksum_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checksum_);
  }
}

void CSMsgPkgHead::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkgHead::CopyFrom(const CSMsgPkgHead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkgHead::IsInitialized() const {

  return true;
}

void CSMsgPkgHead::Swap(CSMsgPkgHead* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkgHead::InternalSwap(CSMsgPkgHead* other) {
  std::swap(msgid_, other->msgid_);
  std::swap(pkgbodylen_, other->pkgbodylen_);
  checksum_.Swap(&other->checksum_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkgHead::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkgHead_descriptor_;
  metadata.reflection = CSMsgPkgHead_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkgHead

// optional uint32 msgID = 1;
void CSMsgPkgHead::clear_msgid() {
  msgid_ = 0u;
}
 ::google::protobuf::uint32 CSMsgPkgHead::msgid() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgHead.msgID)
  return msgid_;
}
 void CSMsgPkgHead::set_msgid(::google::protobuf::uint32 value) {
  
  msgid_ = value;
  // @@protoc_insertion_point(field_set:CSProtocol.CSMsgPkgHead.msgID)
}

// optional uint32 pkgBodyLen = 2;
void CSMsgPkgHead::clear_pkgbodylen() {
  pkgbodylen_ = 0u;
}
 ::google::protobuf::uint32 CSMsgPkgHead::pkgbodylen() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgHead.pkgBodyLen)
  return pkgbodylen_;
}
 void CSMsgPkgHead::set_pkgbodylen(::google::protobuf::uint32 value) {
  
  pkgbodylen_ = value;
  // @@protoc_insertion_point(field_set:CSProtocol.CSMsgPkgHead.pkgBodyLen)
}

// optional string checkSum = 3;
void CSMsgPkgHead::clear_checksum() {
  checksum_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CSMsgPkgHead::checksum() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkgHead.checkSum)
  return checksum_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CSMsgPkgHead::set_checksum(const ::std::string& value) {
  
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CSProtocol.CSMsgPkgHead.checkSum)
}
 void CSMsgPkgHead::set_checksum(const char* value) {
  
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CSProtocol.CSMsgPkgHead.checkSum)
}
 void CSMsgPkgHead::set_checksum(const char* value, size_t size) {
  
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CSProtocol.CSMsgPkgHead.checkSum)
}
 ::std::string* CSMsgPkgHead::mutable_checksum() {
  
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkgHead.checkSum)
  return checksum_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CSMsgPkgHead::release_checksum() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkgHead.checkSum)
  
  return checksum_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CSMsgPkgHead::set_allocated_checksum(::std::string* checksum) {
  if (checksum != NULL) {
    
  } else {
    
  }
  checksum_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), checksum);
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkgHead.checkSum)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CSMsgPkg::kCsMsgPkgHeadFieldNumber;
const int CSMsgPkg::kCsMsgPkgBodyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CSMsgPkg::CSMsgPkg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CSProtocol.CSMsgPkg)
}

void CSMsgPkg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  csmsgpkghead_ = const_cast< ::CSProtocol::CSMsgPkgHead*>(&::CSProtocol::CSMsgPkgHead::default_instance());
  csmsgpkgbody_ = const_cast< ::CSProtocol::CSMsgPkgBody*>(&::CSProtocol::CSMsgPkgBody::default_instance());
}

CSMsgPkg::CSMsgPkg(const CSMsgPkg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CSProtocol.CSMsgPkg)
}

void CSMsgPkg::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  csmsgpkghead_ = NULL;
  csmsgpkgbody_ = NULL;
}

CSMsgPkg::~CSMsgPkg() {
  // @@protoc_insertion_point(destructor:CSProtocol.CSMsgPkg)
  SharedDtor();
}

void CSMsgPkg::SharedDtor() {
  if (this != default_instance_) {
    delete csmsgpkghead_;
    delete csmsgpkgbody_;
  }
}

void CSMsgPkg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CSMsgPkg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgPkg_descriptor_;
}

const CSMsgPkg& CSMsgPkg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CSProtoPkgDef_2eproto();
  return *default_instance_;
}

CSMsgPkg* CSMsgPkg::default_instance_ = NULL;

CSMsgPkg* CSMsgPkg::New(::google::protobuf::Arena* arena) const {
  CSMsgPkg* n = new CSMsgPkg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CSMsgPkg::Clear() {
// @@protoc_insertion_point(message_clear_start:CSProtocol.CSMsgPkg)
  if (GetArenaNoVirtual() == NULL && csmsgpkghead_ != NULL) delete csmsgpkghead_;
  csmsgpkghead_ = NULL;
  if (GetArenaNoVirtual() == NULL && csmsgpkgbody_ != NULL) delete csmsgpkgbody_;
  csmsgpkgbody_ = NULL;
}

bool CSMsgPkg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CSProtocol.CSMsgPkg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CSProtocol.CSMsgPkgHead csMsgPkgHead = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkghead()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_csMsgPkgBody;
        break;
      }

      // optional .CSProtocol.CSMsgPkgBody csMsgPkgBody = 2;
      case 2: {
        if (tag == 18) {
         parse_csMsgPkgBody:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_csmsgpkgbody()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CSProtocol.CSMsgPkg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CSProtocol.CSMsgPkg)
  return false;
#undef DO_
}

void CSMsgPkg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CSProtocol.CSMsgPkg)
  // optional .CSProtocol.CSMsgPkgHead csMsgPkgHead = 1;
  if (this->has_csmsgpkghead()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->csmsgpkghead_, output);
  }

  // optional .CSProtocol.CSMsgPkgBody csMsgPkgBody = 2;
  if (this->has_csmsgpkgbody()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->csmsgpkgbody_, output);
  }

  // @@protoc_insertion_point(serialize_end:CSProtocol.CSMsgPkg)
}

::google::protobuf::uint8* CSMsgPkg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSProtocol.CSMsgPkg)
  // optional .CSProtocol.CSMsgPkgHead csMsgPkgHead = 1;
  if (this->has_csmsgpkghead()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->csmsgpkghead_, false, target);
  }

  // optional .CSProtocol.CSMsgPkgBody csMsgPkgBody = 2;
  if (this->has_csmsgpkgbody()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->csmsgpkgbody_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CSProtocol.CSMsgPkg)
  return target;
}

int CSMsgPkg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CSProtocol.CSMsgPkg)
  int total_size = 0;

  // optional .CSProtocol.CSMsgPkgHead csMsgPkgHead = 1;
  if (this->has_csmsgpkghead()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkghead_);
  }

  // optional .CSProtocol.CSMsgPkgBody csMsgPkgBody = 2;
  if (this->has_csmsgpkgbody()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->csmsgpkgbody_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSMsgPkg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CSProtocol.CSMsgPkg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CSMsgPkg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CSMsgPkg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CSProtocol.CSMsgPkg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CSProtocol.CSMsgPkg)
    MergeFrom(*source);
  }
}

void CSMsgPkg::MergeFrom(const CSMsgPkg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CSProtocol.CSMsgPkg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_csmsgpkghead()) {
    mutable_csmsgpkghead()->::CSProtocol::CSMsgPkgHead::MergeFrom(from.csmsgpkghead());
  }
  if (from.has_csmsgpkgbody()) {
    mutable_csmsgpkgbody()->::CSProtocol::CSMsgPkgBody::MergeFrom(from.csmsgpkgbody());
  }
}

void CSMsgPkg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CSProtocol.CSMsgPkg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSMsgPkg::CopyFrom(const CSMsgPkg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSProtocol.CSMsgPkg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSMsgPkg::IsInitialized() const {

  return true;
}

void CSMsgPkg::Swap(CSMsgPkg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CSMsgPkg::InternalSwap(CSMsgPkg* other) {
  std::swap(csmsgpkghead_, other->csmsgpkghead_);
  std::swap(csmsgpkgbody_, other->csmsgpkgbody_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CSMsgPkg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CSMsgPkg_descriptor_;
  metadata.reflection = CSMsgPkg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CSMsgPkg

// optional .CSProtocol.CSMsgPkgHead csMsgPkgHead = 1;
bool CSMsgPkg::has_csmsgpkghead() const {
  return !_is_default_instance_ && csmsgpkghead_ != NULL;
}
void CSMsgPkg::clear_csmsgpkghead() {
  if (GetArenaNoVirtual() == NULL && csmsgpkghead_ != NULL) delete csmsgpkghead_;
  csmsgpkghead_ = NULL;
}
const ::CSProtocol::CSMsgPkgHead& CSMsgPkg::csmsgpkghead() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkg.csMsgPkgHead)
  return csmsgpkghead_ != NULL ? *csmsgpkghead_ : *default_instance_->csmsgpkghead_;
}
::CSProtocol::CSMsgPkgHead* CSMsgPkg::mutable_csmsgpkghead() {
  
  if (csmsgpkghead_ == NULL) {
    csmsgpkghead_ = new ::CSProtocol::CSMsgPkgHead;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkg.csMsgPkgHead)
  return csmsgpkghead_;
}
::CSProtocol::CSMsgPkgHead* CSMsgPkg::release_csmsgpkghead() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkg.csMsgPkgHead)
  
  ::CSProtocol::CSMsgPkgHead* temp = csmsgpkghead_;
  csmsgpkghead_ = NULL;
  return temp;
}
void CSMsgPkg::set_allocated_csmsgpkghead(::CSProtocol::CSMsgPkgHead* csmsgpkghead) {
  delete csmsgpkghead_;
  csmsgpkghead_ = csmsgpkghead;
  if (csmsgpkghead) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkg.csMsgPkgHead)
}

// optional .CSProtocol.CSMsgPkgBody csMsgPkgBody = 2;
bool CSMsgPkg::has_csmsgpkgbody() const {
  return !_is_default_instance_ && csmsgpkgbody_ != NULL;
}
void CSMsgPkg::clear_csmsgpkgbody() {
  if (GetArenaNoVirtual() == NULL && csmsgpkgbody_ != NULL) delete csmsgpkgbody_;
  csmsgpkgbody_ = NULL;
}
const ::CSProtocol::CSMsgPkgBody& CSMsgPkg::csmsgpkgbody() const {
  // @@protoc_insertion_point(field_get:CSProtocol.CSMsgPkg.csMsgPkgBody)
  return csmsgpkgbody_ != NULL ? *csmsgpkgbody_ : *default_instance_->csmsgpkgbody_;
}
::CSProtocol::CSMsgPkgBody* CSMsgPkg::mutable_csmsgpkgbody() {
  
  if (csmsgpkgbody_ == NULL) {
    csmsgpkgbody_ = new ::CSProtocol::CSMsgPkgBody;
  }
  // @@protoc_insertion_point(field_mutable:CSProtocol.CSMsgPkg.csMsgPkgBody)
  return csmsgpkgbody_;
}
::CSProtocol::CSMsgPkgBody* CSMsgPkg::release_csmsgpkgbody() {
  // @@protoc_insertion_point(field_release:CSProtocol.CSMsgPkg.csMsgPkgBody)
  
  ::CSProtocol::CSMsgPkgBody* temp = csmsgpkgbody_;
  csmsgpkgbody_ = NULL;
  return temp;
}
void CSMsgPkg::set_allocated_csmsgpkgbody(::CSProtocol::CSMsgPkgBody* csmsgpkgbody) {
  delete csmsgpkgbody_;
  csmsgpkgbody_ = csmsgpkgbody;
  if (csmsgpkgbody) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:CSProtocol.CSMsgPkg.csMsgPkgBody)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace CSProtocol

// @@protoc_insertion_point(global_scope)
